app/__init__.py
from flask import Flask, render_template, request, session, flash
from flask_bcrypt import Bcrypt

#Importe de Blurprints
from app.routes.index_routes import bp_index
from app.routes.deptos_routes import bp_deptos
from app.routes.registros_routes import bp_registros

def application():
    app = Flask(__name__)

    #Configuración
    app.secret_key = "M&_S3cr3t_K3&"
    Bcrypt(app)

    #Registro de Blueprint
    app.register_blueprint(bp_index)
    app.register_blueprint(bp_deptos)
    app.register_blueprint(bp_registros)

    #Ruta Metodo para verificar las URL y Redireccionar al Login
    @app.before_request
    def verificar_peticion():
        ruta = request.path
        if not 'name' in session and ruta != "/" and ruta != "/login_access" and not ruta.startswith("/static"):
            flash("Debe Iniciar Sesión","warning")
            return render_template(('login.html'))
    
    return app

app/routes/deptos_routes.py
from flask import Blueprint, request, jsonify
from app.services import deptos_service
import mysql.connector.errors as error

#Blueprint
bp_deptos = Blueprint('deptos', __name__)

#Rutas
@bp_deptos.get('/getDeptos')
def detDeptos():
    try:
        deptos = deptos_service.list_departamentos()
        if deptos:
            return jsonify(deptos)

    except error.Error as e:
        return jsonify(e)
    
    except Exception as ex:
        return jsonify(ex)


@bp_deptos.post('/getMunicipios')
def getMunicipios():
    try: 
        data = request.get_json()
        cod_depto = data.get("codDepto")
        municipios = deptos_service.list_municipios(cod_depto)
        if municipios:
            return jsonify(municipios)
        
    except error.Error as e:
        return jsonify(e)
    
    except Exception as ex:
        return jsonify(ex)

app/routes/index_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session
from flask_bcrypt import Bcrypt
from app.services import usuarios_service, registros_service
import mysql.connector.errors as error

#Blueprint
bp_index = Blueprint('index', __name__)
bcrypt = Bcrypt()

#Rutas
@bp_index.get('/')
def index():
    session.clear()
    return render_template('login.html')

@bp_index.get('/main')
def main():
    conteo = registros_service.count_registros()
    return render_template('main.html', conteo = conteo)

#Ruta Metodo Post Recorrido BD usuarios y perfiles y acceso
@bp_index.post('/login_access')
def login_access():
    try:
        usuario = request.form['userId']
        contrasena = request.form['userPass']

        user = usuarios_service.listar_usuario_nombre(usuario)
        candidate = user[3]
    
        """ if usuario == '' or contrasena == '':
            flash('Debe diligenciar su usuario y contraseña','warning')
            return render_template('login.html') """
        
        if len(user)>0:
            if bcrypt.check_password_hash(candidate, contrasena):
                session['name'] = user[2]
                session['profile'] = user[4]
                session['document'] = user[0]

                if session['profile'] == 1:
                    return redirect(url_for('index.main'))
            else:       
                flash('Usuario o Contraseña Incorrecta', 'warning')
                return render_template('login.html')
        else: 
            flash('Usuario no existe. Contacte al Administrador del Sistema', 'error')
            return render_template('login.html')
        
    except TypeError:
        flash('Usuario no existe. Contacte al Administrador del Sistema', 'error')
        return render_template('login.html')

#Ruta Ventana Retorno Pagina Login    
@bp_index.get('/logout')
def logout():
    session.clear()
    return render_template('login.html')    

app/routes/registros_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from app.services import documentos_service, deptos_service, etnias_service, registros_service
import mysql.connector.errors as error

#Blueprint
bp_registros = Blueprint('registros', __name__)

#Rutas
@bp_registros.get('/registros')
def registros():
    registros = registros_service.list_registros()
    return render_template('tmp_registros/registros.html', registros = registros)

@bp_registros.get('/nuevo_registro')
def nuevo_registro():
    tipos = documentos_service.list_tipoDocumentos()
    deptos = deptos_service.list_departamentos()
    etnias = etnias_service.list_etnias()
    return render_template('tmp_registros/nuevo_registro.html', tipos = tipos, deptos = deptos, etnias = etnias)

@bp_registros.post('/add_registro')
def add_registro():
    try:
        tipo_documento = request.form["tipo_documento"]
        nuip = request.form["nuip"]
        nombre_completo = request.form["nombre_completo"]
        fecha_nacimiento = request.form["fecha_nacimiento"]
        direccion = request.form["direccion"]
        telefono = request.form["telefono"]
        email = request.form["email"]
        depto = request.form["depto"]
        nom_depto = request.form["nom_depto"]
        municipio = request.form["municipio"]
        nom_municipio = request.form["nom_municipio"]
        sexo = request.form["sexo"]
        etnia = request.form["etnia"]
        usuario_registro = request.form["usuario_registro"]

        registros_service.insert_registro(tipo_documento, nuip, nombre_completo, fecha_nacimiento, direccion, telefono,
                                          email, depto, nom_depto, municipio, nom_municipio, sexo, etnia, usuario_registro)
        
        flash("Registro Guardado Exitosamente!", "success")
        return redirect(url_for('index.main'))
    
    except error.Error as e:
        flash(f"Se presentó un error inesperado: {e.msg}", "error")
        return redirect(url_for('index.main'))
    
    except Exception as ex:
        flash(f"Se presentó un error inesperado: {ex}", "error")
        return redirect(url_for('index.main'))

@bp_registros.get('/editar_registro/<int:id>')
def editar_registro(id):
    registro = registros_service.list_registro_id(id)
    tipos = documentos_service.list_tipoDocumentos()
    deptos = deptos_service.list_departamentos()
    etnias = etnias_service.list_etnias()
    return render_template('tmp_registros/editar_registro.html', registro = registro, tipos = tipos, deptos = deptos, etnias = etnias)

@bp_registros.post('/update_registro')
def update_registro():
    try:
        tipo_documento = request.form["tipo_documento"]
        nuip = request.form["nuip"]
        nombre_completo = request.form["nombre_completo"]
        fecha_nacimiento = request.form["fecha_nacimiento"]
        direccion = request.form["direccion"]
        telefono = request.form["telefono"]
        email = request.form["email"]
        depto = request.form["depto"]
        nom_depto = request.form["nom_depto"]
        municipio = request.form["municipio"]
        nom_municipio = request.form["nom_municipio"]
        sexo = request.form["sexo"]
        etnia = request.form["etnia"]
        id_registro = request.form["id_registro"]

        registros_service.update_registro(tipo_documento, nuip, nombre_completo, fecha_nacimiento, direccion, telefono,
                                          email, depto, nom_depto, municipio, nom_municipio, sexo, etnia, id_registro)
        
        flash("Datos de Registro Actualizados Exitosamente", "success")
        return redirect(url_for('registros.registros'))

    except error.Error as e:
        flash(f"Se presentó un error inesperado: {e.msg}", "error")
        return redirect(url_for('registros.registros'))

    except Exception as ex:
        flash(f"Se presentó un error inesperado: {ex}", "error")
        return redirect(url_for('registros.registros'))
 
@bp_registros.get('/getRegistrosDepto')
def getRegistrosDepto():
    try:
        registros_depto = registros_service.count_registros_x_depto()
        if registros_depto:
            return jsonify(registros_depto)

    except Exception as ex:
        return jsonify(ex)        

app/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block css %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>

{% block scripts %}
{% endblock %}
</html>

app/templates/login.html
{% extends 'base.html' %}

{% block css %}
<!-- Bulma Framework -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/bulmaswatch.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/bulma-tooltip.min.css') }}">
<!-- SweetAlert2 -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/sweetalert2.min.css') }}">
<!-- FA Icons -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome-4.7.0/css/font-awesome.min.css')}}">
<!-- Css -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/login-css.css') }}">
{% endblock %}
{% block title %}App Gestión Campaña{% endblock %}

{% block content %}
<div class="container">
    <div class="box login">
        <img class="centrar-imagen" src="{{url_for('static', filename='img/logo2.png')}}" alt="logo_campaña" width="220px" height="220px">
        <!-- <td><img class="centrar-imagen" src="{{url_for('static', filename='assets/logo_empresa.webp')}}" alt="logo_empresa"></td> -->
        <form id="formLoginAccess" action="{{ url_for('index.login_access') }}" method="post">
            <div class="field">
                <p class="control has-icons-left">
                <input class="input" type="text" placeholder="Usuario" name="userId" id="userId">
                <span class="icon is-small is-left">
                    <i class="fa fa-user"></i>
                </span>
                </p>
            </div>
            <div class="field">
                <p class="control has-icons-left">
                <input class="input" type="password" placeholder="Contraseña" name="userPass" id="userPass">
                <span class="icon is-small is-left">
                    <i class="fa fa-lock"></i>
                </span>
                </p>
            </div>
            <div class="field">
                <button type="submit" class="button is-primary is-fullwidth">
                <span class="icon is-small">
                    <i class="fa fa-sign-in"></i>
                </span>
                <span>Iniciar Sesión</span>
                </button>
            </div>
        </form>
        <div class="columns">
            <div class="column is-four-fifths"></div>
            <div class="column">
                <p style="text-align: right;"><strong>v. 1.0.0</strong></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<!-- SweetAlert2 -->
<script src="{{ url_for('static', filename='js/sweetalert2.all.min.js') }}"></script>
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
        <script>
            Swal.fire({
                title: "Notificación!",
                text: "{{ message }}",
                icon: "{{ category }}"
            })
        </script>
        {% endfor %}
    {% endif %}
{% endwith %}

<script src="{{ url_for('static', filename='js/login/login.js') }}"></script>
{% endblock %}

app/templates/main.html
{% extends 'menu.html' %}

{% block css %}
{% endblock %}
{% block title %}Panel Principal{% endblock %}

{% block content %}
<div class="container">
    <br>
    <div class="field is-grouped">
        <p class="control">
            <div class="card">
                <header class="card-header" style="background-color: #8e44ad;">
                    <p class="card-header-title" style="color: white;">Meta Total de Votos</p>
                </header>
                <div class="card-content" style="justify-content: center; align-items: center; display: flex;">
                    <div class="content">
                        <h4 class="title is-4">70.000</h5>
                    </div>
                </div>
            </div>
        </p>
        <p class="control">
            <div class="card">
                <header class="card-header" style="background-color: #8e44ad;">
                    <p class="card-header-title" style="color: white;">Registro de Votos</p>
                </header>
                <div class="card-content" style="justify-content: center; align-items: center; display: flex;">
                    <div class="content">
                        <h4 class="title is-4">{{ conteo[0] }}</h5>
                    </div>
                </div>
            </div>
        </p>
    </div>
    <div class="box">
        <div class="field">
            <p class="control">
                <a href="{{ url_for('registros.nuevo_registro') }}" class="button is-normal is-info is-fullwidth">
                    <span class="icon is-small"><i aria-hidden="true"><img src="{{ url_for('static', filename='img/icons/añadir.png') }}" alt="icon-añadir"></i></span>
                    <span>Nuevo Registro</span>
                </a>
            </p>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        {% for category, message in messages %}
        <script>
            Swal.fire({
                title: "Notificación!",
                text: "{{ message }}",
                icon: "{{ category }}"
            })
        </script>
        {% endfor %}
    {% endif %}
{% endwith %}
{% endblock %}

app/templates/menu.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bulma Framework -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulmaswatch.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma-tooltip.min.css') }}">
    <!-- SweetAlert2 -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sweetalert2.min.css') }}">
    <!-- FA Icons -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome-4.7.0/css/font-awesome.min.css')}}">
    {% block css %}
    {% endblock %}
    <style>
        .main-content {
            padding-top: 3.25rem; /* Altura típica del navbar en Bulma */
        }
    </style>
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <nav class="navbar has-shadow" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a href="#" class="navbar-item">
                <span><strong>Bienvenido(a): </strong>{{ session['name'] }}</span>
                <span hidden>
                    <input type="text" name="profile" id="profile" class="input" value="{{ session['profile'] }}" readonly hidden>
                </span>
            </a>
            <!-- Burger -->
            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div class="navbar-menu" id="navMenu">
            <div class="navbar-start">
                <a href="{{ url_for('index.logout')}}" class="navbar-item">
                    <span class="icon is-small"><img src="{{ url_for('static', filename='img/icons/salida.png') }}" alt="icon-salida"></span>
                    <span>Salir</span>
                </a>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>

<script src="{{ url_for('static', filename='js/sweetalert2.all.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/nav-burger.js') }}"></script>
{% block scripts %}
{% endblock %}
</html>

app/templates/tmp_registros/nuevo_registro.html
{% extends 'menu.html' %}

{% block css %}
{% endblock %}

{% block title %}Nuevo Registro{% endblock %}

{% block content %}
<div class="container">
    <form id="formAddRegistro" action="{{ url_for('registros.add_registro') }}" method="post">
        <div class="card">
            <header class="card-header">
                <p class="card-header-title">Ingrese la información</p>
            </header>
            <div class="card-content">
                <div class="content">
                    <p class="control" hidden>
                        <input type="text" name="usuario_registro" id="usuario_registro" value="{{ session['name'] }}" class="input" readonly>
                    </p>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="tipo_documento" class="label is-small">Tipo documento: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <span class="select is-fullwidth">
                                        <select name="tipo_documento" id="tipo_documento" required>
                                            <option value=""></option>
                                            {% for tipo in tipos %}
                                            <option value="{{ tipo.cod_tipo }}">{{ tipo.nom_tipo }}</option>
                                            {% endfor %}
                                        </select>
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="nuip" class="label">Nro. documento: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input type="text" name="nuip" id="nuip" class="input" required>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="nombre_completo" class="label">Nombre Completo: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input type="text" name="nombre_completo" id="nombre_completo" class="input" required>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="fecha_nacimiento" class="label">Fecha Nacimiento: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input type="date" name="fecha_nacimiento" id="fecha_nacimiento" class="input" required>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="direccion" class="label">Dirección: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input type="text" name="direccion" id="direccion" class="input" required>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="telefono" class="label">Teléfonos: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input type="text" name="telefono" id="telefono" class="input" required>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="email" class="label">Correo electronico: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <input type="email" name="email" id="email" class="input" required>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="depto" class="label">Departamento: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field is-grouped">
                                <p class="control">
                                    <span class="select is-fullwidth">
                                        <select name="depto" id="depto" required>
                                            <option value=""></option>
                                            {% for depto in deptos %}
                                            <option value="{{ depto.cod_depto }}">{{ depto.nom_depto }}</option>
                                            {% endfor %}
                                        </select>
                                    </span>
                                </p>
                                <p class="control is-expanded" hidden>
                                    <input type="text" name="nom_depto" id="nom_depto" class="input" readonly>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="municipio" class="label is-small">Municipio: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field is-grouped">
                                <p class="control">
                                    <span class="select is-fullwidth">
                                        <select name="municipio" id="municipio" required></select>
                                    </span>
                                </p>
                                <p class="control is-expanded" hidden>
                                    <input type="text" name="nom_municipio" id="nom_municipio" class="input" readonly>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="sexo" class="label">Sexo: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <p class="control">
                                    <span class="select is-fullwidth">
                                        <select name="sexo" id="sexo" required>
                                            <option value=""></option>
                                            <option value="H">Hombre</option>
                                            <option value="M">Mujer</option>
                                            <option value="I">Inderterminado o Intersexual</option>
                                        </select>
                                    </span>
                                </p>
                            </div>
                        </div>
                    </div>
                    <div class="field is-horizontal">
                        <div class="field-label">
                            <label for="etnia" class="label">Etnia o Grupo: <strong style="color: red;">*</strong></label>
                        </div>
                        <div class="field-body">
                            <div class="field">
                                <span class="select is-fullwidth" style="font-size: small;">
                                    <select name="etnia" id="etnia" required>
                                        <option value=""></option>
                                        {% for etnia in etnias %}
                                        <option value="{{ etnia.cod_etnia }}">{{ etnia.nom_etnia }}</option>
                                        {% endfor %}
                                    </select>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <button type="submit" class="button is-success is-fullwidth">
                        <span class="icon is-small"><i aria-hidden="true"><img src="{{ url_for('static', filename='img/icons/guardar.png') }}" alt="icon-guardar"></i></span>
                        <span>Guardar</span>
                    </button>
                </div>
                <div class="field">
                    <a id="btn_cancelar" class="button is-danger is-fullwidth">
                        <span class="icon is-small"><i aria-hidden="true"><img src="{{ url_for('static', filename='img/icons/cancelar.png') }}" alt="icon-cancelar"></i></span>
                        <span>Cancelar</span>
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/registros/nuevo_registro.js') }}"></script>
{% endblock %}